# Generated by Django 3.0.7 on 2020-07-10 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=64)),
                ('product_description', models.TextField(blank=True)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('product_url', models.CharField(blank=True, max_length=256)),
                ('product_created', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('kids', 'KIDS'), ('women', 'WOMEN'), ('electronics', 'ELECTRONICS'), ('groceries', 'GROCERIES'), ('other', 'OTHER')], default='other', max_length=14)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
