# Generated by Django 3.0.7 on 2020-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dateCompleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
